testing
badrandom/HW1Local pull request #1
Opened 2020-10-22 13:13 UTC by badrandom

2020-10-22 17:38 UTC, DragonF0rm requested changes

2020-10-22 17:38 UTC, DragonF0rm commented on .idea/gradle.xml
> +  <component name="GradleMigrationSettings" migrationVersion="1" />
Всю .idea следует добавлять в .gitignore, сейчас можно не исправлять, но на будещее её в репу лучше не пушить

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/java/com/example/hw1local/MainActivity.java
> +                    replace(R.id.recycler_fragment, new RecyclerFragment()).commitAllowingStateLoss();
Почему AllowingStateLoss?

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/java/com/example/hw1local/NumberFragment.java
> +
Пиши, пожалуйста, аккуратнее. Пустые строки обычно используются для разделения кода на логические блоки, двойные пустые строки в java писать не принято

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/java/com/example/hw1local/RecyclerFragment.java
> +            col = 3;
Magic numbers - это лучше убрать в ресурсы

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/java/com/example/hw1local/RecyclerFragment.java
> +                holder.txtView.setTextColor(ContextCompat.getColor(getContext(), R.color.colorRed));
Во-первых, почему код в этих строках выглядит по-разному? Когда пишешь части кода, которые делают одно и то же, их стоит писать максимально похожими, тогда это будет проще читать.

Во-вторых, тут перепутаны цвета относительно NumberFragment.java:31. Это потому, что переменным нужно давать имена не по их содержимому, а по цели их использования. В твоём случае лучше переименовать colo.Red и color.Blue на color.Even и color.Odd

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/java/com/example/hw1local/RecyclerFragment.java
> +                            commitAllowingStateLoss();
Снова, почему AllowingStateLoss?

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/res/layout/element_layout.xml
> +        android:textSize="30sp"
Все размеры в ресурсы

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/res/layout/fragment_number.xml
> +        android:textSize="100sp"
В ресурсы

2020-10-22 17:38 UTC, DragonF0rm commented on app/src/main/res/layout/fragment_recycler.xml
> +        android:text="Add"
Все текстовые константы в ресурсы

2020-10-22 17:47 UTC, badrandom commented on app/src/main/java/com/example/hw1local/MainActivity.java
> +                    replace(R.id.recycler_fragment, new RecyclerFragment()).commitAllowingStateLoss();
Просто потому что на лекции преподаватель говорил, что так делать лучше. Если использовать .commit(), то в некоторых случаях приложение крашится. Сейчас, думаю, такой ситуации не может быть, но если, к примеру, я установлю задержку и сверну приложение до того, как строка исполнится, оно вылетит.

2020-10-22 17:50 UTC, badrandom commented on app/src/main/java/com/example/hw1local/NumberFragment.java
> +
А перед методами и новыми классами логично оставлять пробел?

2020-10-23 17:53 UTC, DragonF0rm commented on app/src/main/java/com/example/hw1local/MainActivity.java
> +                    replace(R.id.recycler_fragment, new RecyclerFragment()).commitAllowingStateLoss();
В любом случае, если ты используешь, то должен сам понимать, какие последствия для приложения будут

2020-10-23 18:03 UTC, DragonF0rm approved these changes
Можно мёрджить

2020-10-25 12:43 UTC, merged